### ISSUE TITLE
Python package name is set to zinc, which is used by an existing project on PyPI

### ISSUE THREAD

**Issue by metatoaster** [cmlibs/zinc#112]
https://github.com/OpenCMISS/zinc/blob/77cde7c6ea6ee388de892610d3ea397af3337959/bindings/python/CMakeLists.txt#L166

This should probably be prepended with the project namespace (or just set it to something like `opencmiss.zinc`).

Also, the appropriate namespace should be declared (i.e. add `namespace_packages=['opencmiss'],` to the `setup` call), if `opencmiss` is to be usable as a namespace across different eggs.

**Comment by hsorby** [comment]
I have this change pending somewhere, I just need to find it and create the pull request.

**Comment by hsorby** [comment]
There are a few around the place that need to be done at the same time.

**Comment by chrispbradley** [comment]
The project name should be OpenCMISS on PyPI. This is the only project we have. It should install both components.

**Comment by metatoaster** [comment]
But this is about the Python bindings to the zinc library in OpenCMISS.  I thought there are talks to modularise this project so a Python package that installs _both_ components can be provided (that one can simply be called OpenCMISS, which provide the namespace and have dependencies declared on both or whatever else packages that the OpenCMISS project will provide), but users should have the option to only install the zinc bindings only without having to pull in iron.

**Comment by chrispbradley** [comment]
There is only one OpenCMISS project which comprises zinc and iron components. The agreement was when iron and zinc was decided on that the external name and project was OpenCMISS. We shouldn't have separate iron and zinc externally. If need be the setup.py can take an option to just install iron or zinc but the default OpenCMISS package should be both.

**Comment by metatoaster** [comment]
But this is not how Python packaging works. `setup.py` is for developers to use, end-users using `pip` installing this package from https://pypi.org won't have the option to pass parameters to `setup.py`.  They should simply be able to provide the exact subcomponent. i.e:

```
# install zinc only
pip install opencmiss.zinc
# install iron only
pip install opencmiss.iron

# install all of opencmiss
pip install opencmiss
```

There will need to be three packages registered/created on pypi.

I deal with this issue as a Python programmer, I too have a large umbrella project that is called [`calmjs`](https://github.com/calmjs) that is organized in a way similar to OpenCMISS (i.e. main package, with multiple components); there packages that provides specific integration but I structured this project such that end-users won't have to be forced to install the _entire_ suite.  Users can selectively install the exact packages they need (e.g. `pip install calmjs.webpack` for webpack integration, `pip install calmjs.rjs` for RequireJS integration).

**Comment by rchristie** [comment]
Appears to have been fixed.
