### ISSUE TITLE
Add API for adding shader programs

### ISSUE THREAD

**Issue by hsorby** [cmlibs/zinc#122]
Currently we are not able to specify shader programs through the API.  This would be good for manipulating visualisations of images.

**Comment by alan-wu** [comment]
Most of the current implementations can be reused but requires some update to be more inline with our API standards. I propose naming it cmzn_shader_program.

**Comment by hsorby** [comment]
Are there different types of shader, vertex shader and what not?

**Comment by alan-wu** [comment]
There are different types of shade, we only use two in general and they are fragment and vertex shades, these will be implemented as part of the shader_program.

**Comment by alan-wu** [comment]
Here is a very basic use case of the shaders:

Adjust contrast on two materials (texMat1 and texMat2) with different set of textures:

sm = context.getShadermodule()
#shader program object takes in shaders string and compile them into program at run time
sp = sm.createShaderprogram()
#set the shaders string for both vertex and fragment, lets say this program take in an uniform
#value called minimumIntensity and using it to adjust the contrast of the texture
sp.setVertexString(vertexString)
sp.setFragmentString(fragmentString)
                              
#shader uniforms object provides a list of uniform values to be used by the shaders
su1 = sm.createShaderuniforms()
su1.addUniformReal("minimumIntensity", [0.1]) #array size can be anything between 1 to 4
su2 = sm.createShaderuniforms()
su2.addUniformReal("minimumIntensity", [0.5])
                                   
#pass the program and uniform to the material, note that both the shader program and uniforms can
#be reused and shared by different material but not in this use case.
texMat1.setShaderprogram(sp)
texMat1.setShaderuniforms(su1)

texMat2.setShaderprogram(sp)
texMat2.setShaderuniforms(su2)

In the near future, I would like to pass in per vertex values evaluated from computed field into the shaders with unused texCoord attribute (not buffer for backward compatibility).
