### ISSUE TITLE
Can not import _context

### ISSUE THREAD

**Issue by dijbi** [cmlibs/zinc#137]
Hi

I am trying to use the ICMA Python 2 version (https://github.com/ABI-Software/ICMA), which use OpenCMISS Zinc as a dependency. 
I have a W10, with Python 2.7 under Miniconda.
I have installed the Microsoft Visual C++ Redistributable 2017, used the SDK zipfile for a python 2.7 bindings, installed with `python setup.py install`

I keep getting an import error : 
`    from opencmiss.zinc.context import Context
  File "C:\Users\***\Miniconda2\lib\site-packages\zinc-3.1.2_amd64_windows_python_2.7-py2.7.egg\opencmiss\zinc\context.py", line 17, in <module>
    _context = swig_import_helper()
  File "C:\Users\***\Miniconda2\lib\site-packages\zinc-3.1.2_amd64_windows_python_2.7-py2.7.egg\opencmiss\zinc\context.py", line 16, in swig_import_helper
    return importlib.import_module('_context')
  File "C:\Users\***\Miniconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _context`

I have verified if the path was correct C:\Users\***\Miniconda2\lib\site-packages\zinc-3.1.2_amd64_windows_python_2.7-py2.7.egg\opencmiss\zinc\context.py , verified the sys.path inside python.

I am stuck w/ this error and do know what to do next. Any tips for me ?
Thx in advance

**Comment by hsorby** [comment]
There are a number of issues that can result in this particular error I can list a few of them:

- Using 32 bit Python and not 64 bit Python
- Missing MSVC dlls although this shouldn't be a problem on W10 with the msvcrt dll
- Incompatible Python

**Comment by hsorby** [comment]
The first option should be pretty easy to check.
Second one you can use dependency walker (on the _context.pyd file) and post a picture of all 1st level dependencies
Third you can try installing a 64 bit Python from python.org and use the SDK with that and see if it works.

**Comment by dijbi** [comment]
@hsorby : it was indeed the 32bit vs 64 bit dilemma. Nice catch ! 👍 👍 
I am still struggling w/ others errors, but not Opencmiss related.
Thanks again.
