### ISSUE TITLE
Zinc Python graphics test

### ISSUE THREAD

**Issue by rondiplomatico** [cmlibs/zinc#14]
The test internally fails but yet passes. Needs checking!

Test command: /usr/bin/python "/Users/danielthewicked/opencmiss/src/zinc/bindings/python/tests/graphics_tests/graphicstests.py"
16: Test timeout computed to be: 30
16: ...FE.
16: ======================================================================
16: ERROR: testSceneExport (**main**.GraphicsTestCase)
16: ----------------------------------------------------------------------
16: Traceback (most recent call last):
16:   File "/Users/danielthewicked/opencmiss/src/zinc/bindings/python/tests/graphics_tests/graphicstests.py", line 112, in testSceneExport
16:     stringLoc = outputstring.find('vertices')
16: AttributeError: 'NoneType' object has no attribute 'find'
16: 
16: ======================================================================
16: FAIL: testGraphicsToGlyph (**main**.GraphicsTestCase)
16: ----------------------------------------------------------------------
16: Traceback (most recent call last):
16:   File "/Users/danielthewicked/opencmiss/src/zinc/bindings/python/tests/graphics_tests/graphicstests.py", line 123, in testGraphicsToGlyph
16:     self.assertTrue(glyph.isValid())
16: AssertionError: False is not true
16: 
16: ----------------------------------------------------------------------
16: Ran 6 tests in 0.004s
16: 
16: FAILED (failures=1, errors=1)
3/8 Test #16: Python_Bindings_graphicstests ..........   Passed    0.16 sec

**Comment by rondiplomatico** [comment]
probably gtest -> ctest miscommunication

**Comment by rchristie** [comment]
This hasn't been an issue for some time. Closing.
