### ISSUE TITLE
Fieldmodule writeDescription doesn't write out FieldMeshIntegral

### ISSUE THREAD

**Issue by hsorby** [cmlibs/zinc#231]
The fieldmodule `writeDescription()` method doesn't write out mesh integral fields defined in the fieldmodule.

**Comment by rchristie** [comment]
Nodeset operators are also not serialised.

**Comment by rchristie** [comment]
Also planning to add Field::getClassName() API as need a way to disambiguate field types which do not have derived types they can be cast to for type-specific API. This includes all the mesh and nodeset operators, most arithmetic, logarithmic, logical, vector and matrix and many other fields.
