### ISSUE TITLE
Writing out fieldmodule description causes segfault

### ISSUE THREAD

**Issue by hsorby** [cmlibs/zinc#237]
When I try to serialise the attached exf file I find that the Zinc library is segfaulting when writing out the description. Observed this when using ArgonViewer.
[FieldFitter.exf.txt](https://github.com/OpenCMISS/zinc/files/9313846/FieldFitter.exf.txt)
.

**Comment by rchristie** [comment]
It's missing a string conversion for NOT_APPLICABLE coordinate system type which these fields have which I'll shortly fix.
Note if you create a real-valued finite element field through the API it defaults to RECTANGULAR_CARTESIAN coordinate system type, and you must explicitly set NOT_APPLICABLE if you don't want that.
In EX files and absence of coordinate system type translates to NOT_APPLICABLE; "not applicable" is never written out.
This seems an OK state of affairs.
