### ISSUE TITLE
Segmented data image types

### ISSUE THREAD

**Issue by mathiasroesler** [cmlibs/zinc#285]
I have been using the mapping tools to create segmented data from my masked images and fitting the data to an organ scaffold. However, my masks created with png images do not work but my masks created with jpg images do.  It would be great if png images worked the same as jpg images.

**Comment by hsorby** [comment]
It appears that this problem is due to the PNGs having either [1, 2, 4, 8, or 16 pixel depths](http://www.libpng.org/pub/png/book/chapter08.html). Whereas the Zinc library currently only deals with 8 or 16 pixel depth images.
