### ISSUE TITLE
Evaluate higher derivatives, numerical derivatives

### ISSUE THREAD

**Issue by rchristie** [cmlibs/zinc#36]
Second derivatives are needed for smoothing constraints in fitting, and full derivative support both for higher derivatives and numerical derivatives will permit many fields without derivatives to be used for graphics surface coordinates.

The internal 'basis derivative' field type allows analytic evaluation of finite element fields to arbitrary order, but rather than add this to the API it is better to make the derivative field and derivative evaluations for any field perform its work behind the scenes. The implementation of FE derivatives should allow monomial coefficients for finite element field derivatives of any order to be produced, not the current first-derivative only approach, and refactoring this code is part of this issue.

Some field operators can have analytic higher derivative support added relatively easily, including: arithmetic add, subtract, multiply, (divide not so easily); composite component, concatenate.

When not implemented analytically, derivatives for many other field types can be calculated numerically with one-sided estimation (evaluating the field value or lower derivative at an xi offset of say 1E-6 and taking the difference from values at original xi location).

For efficiency, the implementation of derivatives can take advantage of symmetry of higher derivatives, where d^2/dxi1dxi2 == d^2/dxi2dxi1.

**Comment by rchristie** [comment]
This item was originally on our old tracker:
https://tracker.physiomeproject.org/show_bug.cgi?id=1957
However the scope is reduced to only consider derivatives with respect to element xi, not time or field parameters.

That tracker item notes that users have requested the ability to evaluate the Laplacian of a field,  gradient of gradient.

**Comment by rchristie** [comment]
Initial tests anticipating derivative refactoring were added in commit 232d58be.

**Comment by Jagirhussan** [comment]
It would be great to have an api handle to determine all the derivatives associated with a finite element field at a given xi location. Currently, there is no direct way to access second order derivatives and currently they can to be approximated by an expensive finite difference evaluation from the first derivatives.

**Comment by rchristie** [comment]
# Implementation plan:

1. Add a new internal DerivativeOperator class representing a derivative of a particular order in a given region, with specialisations instantiated to represent derivatives with respect to element xi (for particular mesh/dimension), and eventually also w.r.t. time, finite element field parameters and mixed derivatives. 

2. Each DerivativeOperator is given a unique non-negative index in the region. The real field value cache object will store an array of derivative value caches indexed by this, for rapid look-up. Each derivative cache will have its own evaluationCounter so values for each DerivativeOperator can be cached independently of the field value. Since derivatives are frequently zero, an initial cache optimisation will be to flag a zero result so subsequent evaluations can drop terms.

3. Each DerivativeOperator will reference the next lower DerivativeOperators for its variables to allow evaluations of downstream field derivatives by product and chain rules.

4. The external Differentialoperator type will become a reference to the appropriate internal DerivativeOperator with a term index. A term index of -1 may be used to evaluate all terms; the order of this will be finalised in the development but it is likely all derivatives for the first component will precede those of the second and so on. Higher derivatives may have symmetry of terms, but the complete matrix is expected to be returned even if symmetry is used to reduce work internally.

5. All real-valued field types should implement a new virtual evaluateDerivative() function. Where a particular type or order is unimplemented, these functions should call the base field evaluateNumericalDerivative() function to evaluate derivatives using finite differences of the variables the derivative is with respect to, holding other variables constant.

6. Many field types can have explicit implementations of first and higher derivatives:
   * Finite element field type can compute derivatives w.r.t. xi by manipulating the monomial coefficients. The current 'element field values' object only stores monomials for first derivatives, but this will be extended to any order.
   * Constants have zero derivatives.
   * Add, subtract and component/composite are trivially implemented.
   * Multiplication fields can use product rules including for higher derivatives and partial derivative rules.
   * Many other operators have explicit first derivatives and may have some higher derivatives evaluated via Faa di Bruno's formula.

7. A new FieldDerivativeOperator type will be added to return generalised derivatives; its constructor will take a Differentialoperator argument. The current FieldDerivative taking legacy element xi index will be deprecated. TBD: how the new derivative supports image field derivatives.

**Comment by rchristie** [comment]
Fallback numerical differences added in commit a804054e, merged in pr #142.

**Comment by rchristie** [comment]
Pending changes to finite element derivatives code will remove the ability to compute derivatives of polygon bases as used in cmgui example a7. Note that polygons are trivially converted to simplex elements; attached is a script that does this for cmgui example a7 (extension has .txt added so can be uploaded to github issue).

[polygon_to_wedge.pl.txt](https://github.com/OpenCMISS/zinc/files/3588292/polygon_to_wedge.pl.txt)

**Comment by rchristie** [comment]
Closed by pull request #165.
