### ISSUE TITLE
Zinc binary naming

### ISSUE THREAD

**Issue by hsorby** [cmlibs/zinc#63]
Currently the name of the Zinc binary includes a part representing the sha from git for that source revision.  Originally this was an svn revision number which had some meaning.  This issue is to remove the sha from the name of the Zinc binary and return to using version number only.

**Comment by alan-wu** [comment]
Sounds good and in this case we need to make sure there are binary compatibility between different revision of the same version name. Adding more qualifiers may help such patch version?

**Comment by rchristie** [comment]
Hugh has completed this.
