### ISSUE TITLE
Cannot set the parameter of the last component with cmzn_field_finite_element_set_node_parameters

### ISSUE THREAD

**Issue by alan-wu** [cmlibs/zinc#64]
Internally, this is set with setNodeParameters method but it returns an error code when componentNumber < this->field->number_of_components, this always fail when setting the parameter of the last component.

**Comment by rchristie** [comment]
My bad. Looks like getNodeParameters has the same bug.

**Comment by rchristie** [comment]
Fixed. Closing.
