### ISSUE TITLE
Set Sceneviewer background alpha

### ISSUE THREAD

**Issue by rchristie** [cmlibs/zinc#68]
The Zinc Sceneviewer currently clears colour buffers to a specified background RGB colour but with fixed alpha = 0.0. This is why PNG files, which include alpha, have a transparent background if the OpenGL buffer had alpha planes.

Modern windowing systems may support translucent buffers, and if enabled this means the background colour has no effect in Zinc (except with certain blend functions). Control over the degree of translucency is desirable as one may wish it to be 0.0 (transparent), 1.0 (opaque) or somewhere in between.

We should make the background alpha to default to 1.0, as that is what a user expects when setting the background colour.

We need an API to set the background alpha from 0.0 to 1.0. Setting it to 0.0 will allow current behaviour including transparent backgrounds in output images and also its potential effect on blend functions. It may be worth adding the option for overriding alpha when outputting images.

Most likely we'll just add get/setBackgroundAlpha APIs, but there is the option to get/setBackgroundColourRGBA if preferred.

Since the Sceneviewermodule has a default background colour, it makes sense for it to also have a default alpha or an ability to setDefaultBackgroundColourRGBA consistently with the Sceneviewer API.

**Comment by agarny** [comment]
FWIW, I would personally favour `get/setBackgroundColourRGBA()` (and `get/setDefaultBackgroundColourRGBA()` for the `Sceneviewermodule`).

**Comment by rchristie** [comment]
Completed. Closing.
